# Seoul(main) 클러스터 전용 Karpenter values
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::AccountID:role/rocket-farm-main-karpenter-controller

nodeSelector:
  eks.amazonaws.com/nodegroup: rocket-farm-main-management

tolerations:
  - key: role
    operator: Equal
    value: management
    effect: NoSchedule

settings:
  clusterName: rocket-farm-main
