apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway-scaledobject.yaml
  - auth-service-scaledobject.yaml
  - inventory-service-scaledobject.yaml
  - order-service-scaledobject.yaml
  - payment-service-scaledobject.yaml
  - product-service-scaledobject.yaml
