apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: karpenter-parameterstore
  namespace: karpenter
spec:
  provider:
    aws:
      service: ParameterStore
      region: REPLACE_ME # 환경별 overlay에서 patch
      auth:
        jwt:
          serviceAccountRef:
            name: karpenter
            namespace: karpenter
