apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karpenter-values
  namespace: karpenter
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: karpenter-parameterstore
    kind: SecretStore
  target:
    name: karpenter-values
    creationPolicy: Owner
    template:
      data:
        values.yaml: |
          settings:
            clusterEndpoint: "{{ .eks_endpoint }}"
  data:
    - secretKey: eks_endpoint
      remoteRef:
        key: REPLACE_ME # 환경별 overlay에서 patch
